- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  vars_files:
    - keys.yml
  roles:
    - openstack_infra
  tags:
  - provision_hosts

- hosts: devstack
  gather_facts: false
  vars_files:
    - "global_vars.yml"
  roles:
    - cluster
  tags:
  - prepare_cluster_hosts

- hosts: devstack
  roles:
    - devstack
  tags:
  - install_manila

- hosts: devstack
  roles:
    - devstack_common
  tags:
  - openstack_clients
